import { Link, Outlet, useLocation } from 'react-router-dom'
import { useTheme } from '../hooks/useTheme'
import type { User } from '../types/database'

const navItems = [
  { path: '/dashboard', label: 'Overview', exact: true },
  { path: '/dashboard/employees', label: 'Employees' },
  { path: '/dashboard/sops', label: 'SOPs' },
  { path: '/dashboard/contracts', label: 'Contracts' },
  { path: '/dashboard/pending', label: 'Pending' },
  { path: '/dashboard/settings', label: 'Settings' },
]

export function DashboardLayout({ user, onSignOut }: { user: User; onSignOut: () => void }) {
  const { theme, toggle } = useTheme()
  const location = useLocation()

  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--color-bg)' }}>
      <nav
        className="no-print sticky top-0 z-50 border-b backdrop-blur-sm"
        style={{
          borderColor: 'var(--color-border)',
          backgroundColor: 'color-mix(in srgb, var(--color-bg) 80%, transparent)',
        }}
      >
        <div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-6">
          <Link to="/dashboard" className="text-lg font-semibold tracking-tight" style={{ color: 'var(--color-text)' }}>
            Flodok
          </Link>

          <div className="flex items-center gap-1">
            {navItems.map(item => {
              const isActive = item.exact
                ? location.pathname === item.path
                : location.pathname.startsWith(item.path)
              return (
                <Link
                  key={item.path}
                  to={item.path}
                  className="rounded-md px-3 py-1.5 text-sm font-medium transition-colors"
                  style={{
                    color: isActive ? 'var(--color-primary)' : 'var(--color-text-secondary)',
                    backgroundColor: isActive ? 'color-mix(in srgb, var(--color-primary) 10%, transparent)' : 'transparent',
                  }}
                >
                  {item.label}
                </Link>
              )
            })}
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={toggle}
              className="rounded-md p-1.5 transition-colors hover:opacity-70"
              style={{ color: 'var(--color-text-secondary)' }}
              title={`Switch to ${theme === 'light' ? 'dark' : 'light'} mode`}
            >
              {theme === 'light' ? (
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>
              )}
            </button>
            <span className="text-sm" style={{ color: 'var(--color-text-secondary)' }}>
              {user.name}
            </span>
            <button
              onClick={onSignOut}
              className="rounded-md px-3 py-1.5 text-sm transition-colors hover:opacity-70"
              style={{ color: 'var(--color-text-secondary)' }}
            >
              Sign out
            </button>
          </div>
        </div>
      </nav>

      <main className="mx-auto max-w-6xl px-6 py-8">
        <Outlet />
      </main>
    </div>
  )
}

export function PublicLayout() {
  const { theme, toggle } = useTheme()

  return (
    <div className="min-h-screen" style={{ backgroundColor: 'var(--color-bg)' }}>
      <main className="mx-auto max-w-3xl px-6 py-8">
        <Outlet />
      </main>
      <footer className="border-t py-6 text-center text-sm no-print" style={{ borderColor: 'var(--color-border)', color: 'var(--color-text-tertiary)' }}>
        <div className="flex items-center justify-center gap-3">
          <span>Powered by Flodok</span>
          <button onClick={toggle} className="hover:opacity-70" style={{ color: 'var(--color-text-tertiary)' }}>
            {theme === 'light' ? '🌙' : '☀️'}
          </button>
        </div>
      </footer>
      <div className="print-footer">Generated by Flodok</div>
    </div>
  )
}
