-- Multi-tenant third-party integrations.
--
-- Introduces per-org storage for Fireflies and Asana credentials, replacing
-- the single-tenant Cloudflare KV `config:default` blob. Credentials are
-- AES-256-GCM ciphertext; the key lives in Cloudflare Secrets, so the database
-- alone is not enough to recover a plaintext key.
--
-- The Worker identifies orgs by their existing `organizations.id` UUID.
-- That's auto-generated by Postgres on insert, never collides, never needs
-- backfill, and is already multi-org-compatible if we later add a users
-- → orgs join table. No new identifier column is needed.
--
-- Also introduces:
--   * org_integrations_audit — append-only trail of credential changes.
--   * processed_meetings — atomic dedup store, replaces KV `processed:${id}`
--     (KV is eventually consistent; Postgres insert-on-conflict is not).
--   * processing_logs — per-meeting run log, replaces KV `log:${org}:${id}`.

-- 1. org_integrations ---------------------------------------------------------

create table public.org_integrations (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  provider text not null check (provider in ('fireflies', 'asana')),
  status text not null default 'active' check (status in ('active', 'disabled', 'error')),

  -- AES-256-GCM envelope: "v1." + base64(iv) + "." + base64(ciphertext||tag).
  -- Plaintext is a JSON bag whose shape depends on provider, e.g.
  --   fireflies   -> { api_key, webhook_secret? }
  --   asana       -> { access_token, refresh_token? }
  --   openrouter  -> { api_key, model? }
  --   flodok_api  -> { api_key, api_base }
  credentials_encrypted text not null,

  -- Non-secret config (workspace ids, model names, plan capability flags).
  -- Safe to expose through the public view.
  config jsonb not null default '{}'::jsonb,

  -- Incremented on every credential mutation. The Worker uses this to bust its
  -- KV cache entry without a round trip through Supabase.
  version integer not null default 1,

  last_verified_at timestamptz,
  last_error text,

  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (org_id, provider)
);

create index org_integrations_org_id_idx on public.org_integrations (org_id);
create index org_integrations_status_idx on public.org_integrations (status)
  where status = 'active';

-- Updated-at trigger
create or replace function public.tg_org_integrations_touch()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  if new.credentials_encrypted is distinct from old.credentials_encrypted
     or new.config is distinct from old.config then
    new.version := coalesce(old.version, 0) + 1;
  end if;
  return new;
end;
$$;

create trigger org_integrations_touch
before update on public.org_integrations
for each row execute function public.tg_org_integrations_touch();

-- 2. org_integrations_audit --------------------------------------------------
-- Append-only. Enforced by a trigger rather than application code so no code
-- path can mutate org_integrations without leaving a trail.

create table public.org_integrations_audit (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  integration_id uuid references public.org_integrations(id) on delete set null,
  provider text not null,
  action text not null check (action in (
    'create', 'update', 'rotate', 'delete',
    'test_success', 'test_failure', 'status_change'
  )),
  actor_user_id uuid references public.users(id) on delete set null,
  changed_fields text[],
  detail jsonb,
  at timestamptz not null default now()
);

create index org_integrations_audit_org_idx
  on public.org_integrations_audit (org_id, at desc);
create index org_integrations_audit_integration_idx
  on public.org_integrations_audit (integration_id, at desc);

create or replace function public.tg_org_integrations_audit()
returns trigger
language plpgsql
security definer
as $$
declare
  changed text[] := array[]::text[];
  act text;
begin
  if tg_op = 'INSERT' then
    act := 'create';
    insert into public.org_integrations_audit (
      org_id, integration_id, provider, action, actor_user_id, changed_fields, detail
    ) values (
      new.org_id, new.id, new.provider, act, new.created_by, null,
      jsonb_build_object('status', new.status)
    );
    return new;
  elsif tg_op = 'UPDATE' then
    if new.credentials_encrypted is distinct from old.credentials_encrypted then
      changed := changed || 'credentials_encrypted';
    end if;
    if new.config is distinct from old.config then
      changed := changed || 'config';
    end if;
    if new.status is distinct from old.status then
      changed := changed || 'status';
    end if;
    if new.last_error is distinct from old.last_error then
      changed := changed || 'last_error';
    end if;
    if new.last_verified_at is distinct from old.last_verified_at then
      changed := changed || 'last_verified_at';
    end if;

    if 'credentials_encrypted' = any(changed) then
      act := 'rotate';
    elsif 'status' = any(changed) then
      act := 'status_change';
    elsif array_length(changed, 1) is null then
      return new;
    else
      act := 'update';
    end if;

    insert into public.org_integrations_audit (
      org_id, integration_id, provider, action, actor_user_id, changed_fields, detail
    ) values (
      new.org_id, new.id, new.provider, act, auth.uid(), changed,
      jsonb_build_object(
        'old_status', old.status,
        'new_status', new.status
      )
    );
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.org_integrations_audit (
      org_id, integration_id, provider, action, actor_user_id, changed_fields, detail
    ) values (
      old.org_id, old.id, old.provider, 'delete', auth.uid(), null,
      jsonb_build_object('status', old.status)
    );
    return old;
  end if;
  return null;
end;
$$;

create trigger org_integrations_audit_ins
after insert on public.org_integrations
for each row execute function public.tg_org_integrations_audit();

create trigger org_integrations_audit_upd
after update on public.org_integrations
for each row execute function public.tg_org_integrations_audit();

create trigger org_integrations_audit_del
after delete on public.org_integrations
for each row execute function public.tg_org_integrations_audit();

-- 3. processed_meetings -------------------------------------------------------
-- Atomic dedup: `insert ... on conflict do nothing returning 1` wins the race.
-- Service role only; the Worker goes through the worker-config Edge Function.

create table public.processed_meetings (
  org_id uuid not null references public.organizations(id) on delete cascade,
  provider text not null,
  external_id text not null,
  processed_at timestamptz not null default now(),
  status text not null default 'ok' check (status in ('ok', 'error', 'skipped')),
  detail jsonb,
  primary key (org_id, provider, external_id)
);

create index processed_meetings_org_at_idx
  on public.processed_meetings (org_id, processed_at desc);

-- 4. processing_logs ----------------------------------------------------------
-- Replaces KV `log:${org_id}:${meeting_id}` writes from processor.ts.

create table public.processing_logs (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  provider text not null,
  external_id text not null,
  meeting_title text,
  meeting_date timestamptz,
  employees_matched integer not null default 0,
  tasks_created integer not null default 0,
  sop_updates_sent integer not null default 0,
  unmatched_items integer not null default 0,
  errors jsonb,
  processed_at timestamptz not null default now()
);

create index processing_logs_org_at_idx
  on public.processing_logs (org_id, processed_at desc);
create index processing_logs_external_idx
  on public.processing_logs (org_id, provider, external_id);

-- 5. RLS ---------------------------------------------------------------------

alter table public.org_integrations enable row level security;
alter table public.org_integrations_audit enable row level security;
alter table public.processed_meetings enable row level security;
alter table public.processing_logs enable row level security;

-- org_integrations: the base table holds ciphertext. Do not grant select on it
-- to authenticated users at all. The UI reads from the view below.
revoke all on public.org_integrations from authenticated, anon;

-- Admin/owner can insert/update/delete their own org's rows. The returning row
-- will include the ciphertext, which is fine for the admin who just wrote it.
create policy "Admins manage own org integrations"
  on public.org_integrations for all
  to authenticated
  using (
    org_id = public.get_user_org_id()
    and public.get_user_role() in ('owner', 'admin')
  )
  with check (
    org_id = public.get_user_org_id()
    and public.get_user_role() in ('owner', 'admin')
  );

-- Grant explicit column-level access so a forgotten select doesn't leak
-- credentials_encrypted. Admins still need insert/update/delete privileges.
grant insert, update, delete on public.org_integrations to authenticated;

-- Public view exposes everything except credentials_encrypted. UI uses this.
create or replace view public.org_integrations_public as
select
  id,
  org_id,
  provider,
  status,
  config,
  version,
  last_verified_at,
  last_error,
  created_by,
  created_at,
  updated_at,
  case
    when credentials_encrypted is not null then true
    else false
  end as has_credentials
from public.org_integrations;

grant select on public.org_integrations_public to authenticated;

alter view public.org_integrations_public set (security_invoker = true);

-- Policy on the view is inherited via security_invoker; add one on the base
-- table for select-by-admin that the view will use.
create policy "Admins view own org integrations metadata"
  on public.org_integrations for select
  to authenticated
  using (
    org_id = public.get_user_org_id()
    and public.get_user_role() in ('owner', 'admin')
  );

-- Audit: admins can read their own org's audit trail.
create policy "Admins view own org integration audit"
  on public.org_integrations_audit for select
  to authenticated
  using (
    org_id = public.get_user_org_id()
    and public.get_user_role() in ('owner', 'admin')
  );

-- processed_meetings + processing_logs are service-role only for writes.
-- Managers can read processing_logs for their org (useful for UI history).
create policy "Members view own org processing logs"
  on public.processing_logs for select
  to authenticated
  using (org_id = public.get_user_org_id());

-- No select policy on processed_meetings for authenticated; service role bypasses RLS.

-- 6. Cleanup helper ----------------------------------------------------------
-- Meant to be scheduled (pg_cron or external cron calling an Edge Function).
-- Keeps 90 days of dedup rows; older entries are safe to drop because the
-- providers won't resend meetings older than their own retention window.

create or replace function public.cleanup_processed_meetings(retention_days int default 90)
returns integer
language plpgsql
security definer
as $$
declare
  deleted_count integer;
begin
  delete from public.processed_meetings
  where processed_at < now() - (retention_days || ' days')::interval;
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;
